ARG TARGET_ARCHITECTURE=x86_64-unknown-linux-gnu

FROM rust:1.83-slim-bullseye
ARG TARGET_ARCHITECTURE

RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    libssl-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add ${TARGET_ARCHITECTURE}

WORKDIR /code
RUN mkdir src && echo 'fn main() {println!("hello world");}' > src/main.rs
COPY Cargo.* .

RUN cargo build --release --target=${TARGET_ARCHITECTURE}
RUN rm -rf src/ target/${TARGET_ARCHITECTURE}/release/.fingerprint/canibeloud-*
